{% set data= load_setup_py_data() %}
package:
  name: ts-pmd
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: generic
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  script_env:
    - PATH
    - PYTHONPATH
    - LD_LIBRARY_PATH
    - OSPL_HOME
    - PYTHON_BUILD_VERSION
    - PYTHON_BUILD_LOCATION
    - LSST_DDS_DOMAIN
    - TS_CONFIG_OCS_DIR

test:
  requires:
    - ts-conda-build= 0.3
    - ts-dds
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
    - ts-utils
    - ts-tcpip
  source_files:
    - python
    - bin
    - tests
    - setup.cfg
  commands:
    - pytest

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
  build:
    - python {{ python }}
    - setuptools_scm
    - setuptools
    - ts-conda-build =0.3
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - ts-salobj
    - ts-idl
    - ts-tcpip
